version: '3.7'
services:
  mongo:
    image: mongo:4.1.10-bionic
    restart: always
    ports:
    - 27017:27017
    volumes:
    - db:/data/db
    - configdb:/data/configdb
volumes:
  db:
  configdb:
